name: 'Debug with tmate'
description: 'Debug your GitHub Actions Environment via a secured tmate.io ssh session sent to Slack on build failure'
author: 'Max Schmitt, Keith Bentrup'
runs:
  using: 'node12'
  main: 'setup.js'